In [10]:
#IMPORTING DATASET(.CSV) INTO PANDAS DATAFRAME
import pandas as pd
df = pd.read_csv('02_May_12_covid_impact_survey.csv',
                       sep=',',
                       index_col=False,
                       dtype='unicode')
df

,Unnamed: 0,SU_ID,P_PANEL,NATIONAL_WEIGHT,REGION_WEIGHT,NATIONAL_WEIGHT_POP,REGION_WEIGHT_POP,NAT_WGT_COMB_POP,REG_WGT_COMB_POP,P_GEO,...,REGION9,P_DENSE,MODE,LANGUAGE,MAIL50,RACE1_BANNER,RACE2_BANNER,INC_BANNER,AGE_BANNER,HH_BANNER
0,1,0020000024,ABS,NaN,0.4062974839,NaN,3173.3430006,NaN,1586.6715003,Oregon,...,(9) Pacific,(2) Suburban,(2) Web Interview,(1) English,(5) 5/4/2020,(1) NH white 5,NaN,(2) $30k to less than $60k,(3) 65+,(5) Other
1,2,0020001653,ABS,NaN,0.3187468867,NaN,5219.8516329,NaN,2609.9258164,"Chicago-Naperville-Elgin, Illinois-Indiana-Wis...",...,(3) East North Central,(3) Urban,(2) Web Interview,(1) English,(5) 5/4/2020,(1) NH white 5,NaN,(3) $60k to less than $125k,(2) 23-64,(1) Alone
2,3,0020001908,ABS,NaN,0.5459146697,NaN,5772.0106614,NaN,2886.0053307,Minnesota,...,(4) West North Central,(2) Suburban,(2) Web Interview,(1) English,(5) 5/4/2020,(1) NH white 5,NaN,"(1) Less than $30,000",(3) 65+,(1) Alone
3,4,0020002623,ABS,NaN,0.9353794308,NaN,9912.1956886,NaN,4956.0978443,Colorado,...,(8) Mountain,(3) Urban,(1) Phone interview,(1) English,(5) 5/4/2020,(88) Removed for disclosure risk,NaN,(3) $60k to less than $125k,(2) 23-64,(1) Alone
4,5,0020007751,ABS,NaN,1.4608136632,NaN,6381.6526066,NaN,3190.8263033,"Columbus, Ohio",...,(3) East North Central,(3) Urban,(2) Web Interview,(1) English,(5) 5/4/2020,(1) NH white 5,NaN,(3) $60k to less than $125k,(3) 65+,(2) +1 other adult only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,8970,0040008564,Amerispeak,0.138111,NaN,NaN,NaN,NaN,NaN,NaN,...,(8) Mountain,(3) Urban,(2) Web Interview,(1) English,NaN,(1) NH white 5,NaN,(2) $30k to less than $60k,(3) 65+,(5) Other
8970,8971,0040008565,Amerispeak,1.34786936,NaN,NaN,NaN,NaN,NaN,NaN,...,(1) New England,(3) Urban,(2) Web Interview,(1) English,NaN,(1) NH white 5,NaN,(4) More than $125k,(2) 23-64,(1) Alone
8971,8972,0040008566,Amerispeak,0.7866569101,NaN,NaN,NaN,NaN,NaN,NaN,...,(3) East North Central,(2) Suburban,(2) Web Interview,(1) English,NaN,(1) NH white 5,NaN,(2) $30k to less than $60k,(2) 23-64,(3) 1 or 2 kids
8972,8973,0040008567,Amerispeak,0.5721682663,NaN,NaN,NaN,NaN,NaN,NaN,...,(3) East North Central,(2) Suburban,(2) Web Interview,(1) English,NaN,(1) NH white 5,NaN,(3) $60k to less than $125k,(3) 65+,(2) +1 other adult only
8973,8974,0040008569,Amerispeak,0.8579810309,0.5002794999,NaN,25194.541595,NaN,12597.270797,Texas,...,(7) West South Central,(3) Urban,(2) Web Interview,(1) English,NaN,(3) Hispanic 5,NaN,(2) $30k to less than $60k,(2) 23-64,(1) Alone

In [11]:
#CONVERTING CATEGORICAL TO NUMERICAL DATA
import pandas as pd
# df=pd.get_dummies(df,columns=['COLUMN_A'])
# df=pd.get_dummies(df,columns=['SU_ID'])
df=pd.get_dummies(df,columns=['P_PANEL'])
# df=pd.get_dummies(df,columns=['NATIONAL_WEIGHT'])
# df=pd.get_dummies(df,columns=['REGION_WEIGHT'])
# df=pd.get_dummies(df,columns=['NATIONAL_WEIGHT_POP'])
# df=pd.get_dummies(df,columns=['REGION_WEIGHT_POP'])
# df=pd.get_dummies(df,columns=['NAT_WGT_COMB_POP'])
# df=pd.get_dummies(df,columns=['REG_WGT_COMB_POP'])
# df=pd.get_dummies(df,columns=['P_GEO'])
df=pd.get_dummies(df,columns=['SOC1'])
df=pd.get_dummies(df,columns=['SOC2A'])
df=pd.get_dummies(df,columns=['SOC2B'])
df=pd.get_dummies(df,columns=['SOC3A'])
df=pd.get_dummies(df,columns=['SOC3B'])
df=pd.get_dummies(df,columns=['SOC4A'])
df=pd.get_dummies(df,columns=['SOC4B'])
df=pd.get_dummies(df,columns=['PHYS8'])
df=pd.get_dummies(df,columns=['PHYS1A'])
df=pd.get_dummies(df,columns=['PHYS1B'])
df=pd.get_dummies(df,columns=['PHYS1C'])
df=pd.get_dummies(df,columns=['PHYS1D'])
df=pd.get_dummies(df,columns=['PHYS1E'])
df=pd.get_dummies(df,columns=['PHYS1F'])
df=pd.get_dummies(df,columns=['PHYS1G'])
df=pd.get_dummies(df,columns=['PHYS1H'])
df=pd.get_dummies(df,columns=['PHYS1I'])
df=pd.get_dummies(df,columns=['PHYS1J'])
df=pd.get_dummies(df,columns=['PHYS1K'])
df=pd.get_dummies(df,columns=['PHYS1L'])
df=pd.get_dummies(df,columns=['PHYS1M'])
df=pd.get_dummies(df,columns=['PHYS1N'])
df=pd.get_dummies(df,columns=['PHYS1O'])
df=pd.get_dummies(df,columns=['PHYS1P'])
df=pd.get_dummies(df,columns=['PHYS1Q'])
df=pd.get_dummies(df,columns=['SOC5A'])
df=pd.get_dummies(df,columns=['SOC5B'])
df=pd.get_dummies(df,columns=['SOC5C'])
df=pd.get_dummies(df,columns=['SOC5D'])
df=pd.get_dummies(df,columns=['SOC5E'])
df=pd.get_dummies(df,columns=['PHYS2_1'])
df=pd.get_dummies(df,columns=['PHYS2_2'])
df=pd.get_dummies(df,columns=['PHYS2_3'])
df=pd.get_dummies(df,columns=['PHYS2_4'])
df=pd.get_dummies(df,columns=['PHYS2_5'])
df=pd.get_dummies(df,columns=['PHYS2_6'])
df=pd.get_dummies(df,columns=['PHYS2_7'])
df=pd.get_dummies(df,columns=['PHYS2_8'])
df=pd.get_dummies(df,columns=['PHYS2_9'])
df=pd.get_dummies(df,columns=['PHYS2_10'])
df=pd.get_dummies(df,columns=['PHYS2_11'])
df=pd.get_dummies(df,columns=['PHYS2_12'])
df=pd.get_dummies(df,columns=['PHYS2_13'])
df=pd.get_dummies(df,columns=['PHYS2_14'])
df=pd.get_dummies(df,columns=['PHYS2_15'])
df=pd.get_dummies(df,columns=['PHYS2_16'])
df=pd.get_dummies(df,columns=['PHYS2_17'])
df=pd.get_dummies(df,columns=['PHYS2_18'])
df=pd.get_dummies(df,columns=['PHYS2_19'])
df=pd.get_dummies(df,columns=['PHYS2_DK'])
df=pd.get_dummies(df,columns=['PHYS2_SKP'])
df=pd.get_dummies(df,columns=['PHYS2_REF'])
df=pd.get_dummies(df,columns=['PHYS10A'])
df=pd.get_dummies(df,columns=['PHYS10B'])
df=pd.get_dummies(df,columns=['PHYS10C'])
df=pd.get_dummies(df,columns=['PHYS10D'])
df=pd.get_dummies(df,columns=['PHYS10E'])
df=pd.get_dummies(df,columns=['ECON8A'])
df=pd.get_dummies(df,columns=['ECON8B'])
df=pd.get_dummies(df,columns=['ECON8C'])
df=pd.get_dummies(df,columns=['ECON8D'])
df=pd.get_dummies(df,columns=['ECON8E'])
df=pd.get_dummies(df,columns=['ECON8F'])
df=pd.get_dummies(df,columns=['ECON8G'])
df=pd.get_dummies(df,columns=['ECON8H'])
df=pd.get_dummies(df,columns=['ECON8I'])
df=pd.get_dummies(df,columns=['ECON8J'])
df=pd.get_dummies(df,columns=['ECON8K'])
df=pd.get_dummies(df,columns=['ECON8L'])
df=pd.get_dummies(df,columns=['ECON8M'])
df=pd.get_dummies(df,columns=['ECON8N'])
df=pd.get_dummies(df,columns=['ECON8O'])
df=pd.get_dummies(df,columns=['ECON8P'])
df=pd.get_dummies(df,columns=['ECON8Q'])
df=pd.get_dummies(df,columns=['ECON8R'])
df=pd.get_dummies(df,columns=['ECON8S'])
df=pd.get_dummies(df,columns=['ECON7_1'])
df=pd.get_dummies(df,columns=['ECON7_2'])
df=pd.get_dummies(df,columns=['ECON7_3'])
df=pd.get_dummies(df,columns=['ECON7_4'])
df=pd.get_dummies(df,columns=['ECON7_5'])
df=pd.get_dummies(df,columns=['ECON7_6'])
df=pd.get_dummies(df,columns=['ECON7_7'])
df=pd.get_dummies(df,columns=['ECON7_8'])
df=pd.get_dummies(df,columns=['ECON7_DK'])
df=pd.get_dummies(df,columns=['ECON7_SKP'])
df=pd.get_dummies(df,columns=['ECON7_REF'])
df=pd.get_dummies(df,columns=['ECON1'])
# df=pd.get_dummies(df,columns=['ECON2'])
# df=pd.get_dummies(df,columns=['ECON4'])
df=pd.get_dummies(df,columns=['ECON3'])
df=pd.get_dummies(df,columns=['ECON4A'])
df=pd.get_dummies(df,columns=['ECON4B'])
df=pd.get_dummies(df,columns=['ECON6A'])
df=pd.get_dummies(df,columns=['ECON6B'])
df=pd.get_dummies(df,columns=['ECON6C'])
df=pd.get_dummies(df,columns=['ECON6D'])
df=pd.get_dummies(df,columns=['ECON6E'])
df=pd.get_dummies(df,columns=['ECON6F'])
df=pd.get_dummies(df,columns=['ECON6G'])
df=pd.get_dummies(df,columns=['ECON6H'])
df=pd.get_dummies(df,columns=['ECON6I'])
df=pd.get_dummies(df,columns=['ECON6J'])
df=pd.get_dummies(df,columns=['ECON6K'])
df=pd.get_dummies(df,columns=['ECON6L'])
df=pd.get_dummies(df,columns=['ECON5A_A'])
df=pd.get_dummies(df,columns=['ECON5A_B'])
df=pd.get_dummies(df,columns=['PHYS7_1'])
df=pd.get_dummies(df,columns=['PHYS7_2'])
df=pd.get_dummies(df,columns=['PHYS7_3'])
df=pd.get_dummies(df,columns=['PHYS7_4'])
df=pd.get_dummies(df,columns=['PHYS7_DK'])
df=pd.get_dummies(df,columns=['PHYS7_SKP'])
df=pd.get_dummies(df,columns=['PHYS7_REF'])
df=pd.get_dummies(df,columns=['PHYS11'])
# df=pd.get_dummies(df,columns=['PHYS11_TEMP'])
df=pd.get_dummies(df,columns=['PHYS9A'])
df=pd.get_dummies(df,columns=['PHYS9B'])
df=pd.get_dummies(df,columns=['PHYS9C'])
df=pd.get_dummies(df,columns=['PHYS9D'])
df=pd.get_dummies(df,columns=['PHYS9E'])
df=pd.get_dummies(df,columns=['PHYS9F'])
df=pd.get_dummies(df,columns=['PHYS9G'])
df=pd.get_dummies(df,columns=['PHYS9H'])
df=pd.get_dummies(df,columns=['PHYS3A'])
df=pd.get_dummies(df,columns=['PHYS3B'])
df=pd.get_dummies(df,columns=['PHYS3C'])
df=pd.get_dummies(df,columns=['PHYS3D'])
df=pd.get_dummies(df,columns=['PHYS3E'])
df=pd.get_dummies(df,columns=['PHYS3F'])
df=pd.get_dummies(df,columns=['PHYS3G'])
df=pd.get_dummies(df,columns=['PHYS3H'])
df=pd.get_dummies(df,columns=['PHYS3I'])
df=pd.get_dummies(df,columns=['PHYS3J'])
df=pd.get_dummies(df,columns=['PHYS3K'])
df=pd.get_dummies(df,columns=['PHYS3L'])
df=pd.get_dummies(df,columns=['PHYS3M'])
df=pd.get_dummies(df,columns=['PHYS4'])
df=pd.get_dummies(df,columns=['PHYS5'])
df=pd.get_dummies(df,columns=['PHYS6'])
df=pd.get_dummies(df,columns=['AGE4'])
df=pd.get_dummies(df,columns=['AGE7'])
df=pd.get_dummies(df,columns=['GENDER'])
df=pd.get_dummies(df,columns=['RACETH'])
df=pd.get_dummies(df,columns=['RACE_R2'])
df=pd.get_dummies(df,columns=['HHINCOME'])
df=pd.get_dummies(df,columns=['EDUCATION'])
df=pd.get_dummies(df,columns=['EDUC4'])
# df=pd.get_dummies(df,columns=['P_OCCUPY2'])
# df=pd.get_dummies(df,columns=['MARITAL'])
# df=pd.get_dummies(df,columns=['LGBT'])
df=pd.get_dummies(df,columns=['HHSIZE1'])
df=pd.get_dummies(df,columns=['HH01S'])
df=pd.get_dummies(df,columns=['HH25S'])
df=pd.get_dummies(df,columns=['HH612S'])
df=pd.get_dummies(df,columns=['HH1317S'])
df=pd.get_dummies(df,columns=['HH18OVS'])
df=pd.get_dummies(df,columns=['REGION4'])
df=pd.get_dummies(df,columns=['REGION9'])
df=pd.get_dummies(df,columns=['P_DENSE'])
df=pd.get_dummies(df,columns=['MODE'])
df=pd.get_dummies(df,columns=['LANGUAGE'])
# df=pd.get_dummies(df,columns=['MAIL50'])
# df=pd.get_dummies(df,columns=['RACE1_BANNER'])
# df=pd.get_dummies(df,columns=['RACE2_BANNER'])
# df=pd.get_dummies(df,columns=['INC_BANNER'])
# df=pd.get_dummies(df,columns=['AGE_BANNER'])
# df=pd.get_dummies(df,columns=['HH_BANNER'])

df

,Unnamed: 0,SU_ID,NATIONAL_WEIGHT,REGION_WEIGHT,NATIONAL_WEIGHT_POP,REGION_WEIGHT_POP,NAT_WGT_COMB_POP,REG_WGT_COMB_POP,P_GEO,ECON2,...,REGION9_(7) West South Central,REGION9_(8) Mountain,REGION9_(9) Pacific,P_DENSE_(1) Rural,P_DENSE_(2) Suburban,P_DENSE_(3) Urban,MODE_(1) Phone interview,MODE_(2) Web Interview,LANGUAGE_(1) English,LANGUAGE_(2) Spanish
0,1,0020000024,NaN,0.4062974839,NaN,3173.3430006,NaN,1586.6715003,Oregon,NaN,...,0,0,1,0,1,0,0,1,1,0
1,2,0020001653,NaN,0.3187468867,NaN,5219.8516329,NaN,2609.9258164,"Chicago-Naperville-Elgin, Illinois-Indiana-Wis...",40,...,0,0,0,0,0,1,0,1,1,0
2,3,0020001908,NaN,0.5459146697,NaN,5772.0106614,NaN,2886.0053307,Minnesota,NaN,...,0,0,0,0,1,0,0,1,1,0
3,4,0020002623,NaN,0.9353794308,NaN,9912.1956886,NaN,4956.0978443,Colorado,39,...,0,1,0,0,0,1,1,0,1,0
4,5,0020007751,NaN,1.4608136632,NaN,6381.6526066,NaN,3190.8263033,"Columbus, Ohio",NaN,...,0,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,8970,0040008564,0.138111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,0,1,0,1,1,0
8970,8971,0040008565,1.34786936,NaN,NaN,NaN,NaN,NaN,NaN,45,...,0,0,0,0,0,1,0,1,1,0
8971,8972,0040008566,0.7866569101,NaN,NaN,NaN,NaN,NaN,NaN,25,...,0,0,0,0,1,0,0,1,1,0
8972,8973,0040008567,0.5721682663,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,1,1,0
8973,8974,0040008569,0.8579810309,0.5002794999,NaN,25194.541595,NaN,12597.270797,Texas,40,...,1,0,0,0,0,1,0,1,1,0

In [12]:
#EXPORTING CLEANED DATASET
from pathlib import Path
filepath = Path('C:\python\cleaned_dataset.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(filepath)